project:
  type: website

website:
  title: Text Parsing Package
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Reference"
        href: reference/index.qmd
      - text: "About"
        href: docs/about.qmd
      - text: "Discussion"
        href: docs/discussion.qmd

# tell quarto to read the generated sidebar
metadata-files:
  - reference/_sidebar.yml

# tell quarto to read the generated styles
format:
  html:
    theme: superhero
    css:
      - reference/_styles-quartodoc.css

quartodoc:
  # the name used to import the package you want to create reference docs for
  package: text_parsing_package

  # write sidebar and style data
  sidebar: reference/_sidebar.yml
  css: reference/_styles-quartodoc.css

  sections:
    - title: Text Parsing Functions
      desc: Functions to inspect docstrings.
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - clean_text
        - count_unique_words
        - word_chart